# Lab | Pandas Deep-Dive

### 1. Import Pandas package under the alias pd and Numpy under the alias np

In [63]:
import pandas as pd
import numpy as np

### 2. Define a variable called `path` that contains the path to the csv file you downloaded. 

In [111]:
# Expresión de Python que se utiliza para especificar la ubicación de un archivo CSV

path = 'data/apple_store.csv'

### 3. Using the Pandas `read_csv()` method, import the csv file at the path above. 

Assign the returned value to a variable called `data`.

Note: you can omit the `sep` parameter for `read_csv()` because the csv file uses the default separator of ",".

In [112]:
# Esta línea de código se usa para leer un archivo CSV en un DataFrame de pandas. 
# El argumento `path` especifica la ubicación del archivo CSV que se va a leer. La función `pd.read_csv()` devuelve
# un DataFrame con los datos del archivo CSV y lo almacena en la variable `data`

data = pd.read_csv(path)

### 4. Print the first 5 rows of `data` to see what the data look like.

A data analyst usually does this to have a general understanding about what the data look like before digging deep.

In [113]:
# Función de Pandas que se utiliza para obtener las 5 primeras filas de un conjunto de datos.

data.head()

id                                         track_name  size_bytes  \
0  281656475                                    PAC-MAN Premium   100788224   
1  281796108                          Evernote - stay organized   158578688   
2  281940292    WeatherBug - Local Weather, Radar, Maps, Alerts   100524032   
3  282614216  eBay: Best App to Buy, Sell, Save! Online Shop...   128512000   
4  282935706                                              Bible    92774400   

   price  rating_count_tot  rating_count_ver  user_rating  user_rating_ver  \
0   3.99             21292                26          4.0              4.5   
1   0.00            161065                26          4.0              3.5   
2   0.00            188583              2822          3.5              4.5   
3   0.00            262241               649          4.0              4.5   
4   0.00            985920              5320          4.5              5.0   

    prime_genre  
0         Games  
1  Productivity  
2       Weather  
3      Shopping  
4     Reference

### 5. Print the summary (info) of the data.

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7197 entries, 0 to 7196
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                7197 non-null   int64  
 1   track_name        7197 non-null   object 
 2   size_bytes        7197 non-null   int64  
 3   price             7197 non-null   float64
 4   rating_count_tot  7197 non-null   int64  
 5   rating_count_ver  7197 non-null   int64  
 6   user_rating       7197 non-null   float64
 7   user_rating_ver   7197 non-null   float64
 8   prime_genre       7197 non-null   object 
dtypes: float64(3), int64(4), object(2)
memory usage: 506.2+ KB


### 6. Print the number of columns in the data.

In [114]:
# Se utiliza para calcular el número de columnas en un conjunto de datos.

print(len(data.columns))

9


### 7. Print all column names.

In [115]:
# Expresión de Python que se utiliza para iterar sobre las columnas de un conjunto de datos.
# Esta expresión primero obtiene las columnas del conjunto de datos utilizando la propiedad .columns, 
# y luego itera sobre cada columna. Esta expresión es útil para realizar operaciones en cada columna del conjunto de datos.

for col in data.columns:
    print(col)

id
track_name
size_bytes
price
rating_count_tot
rating_count_ver
user_rating
user_rating_ver
prime_genre


## Now that we have a general understanding of the data, we'll start working on the challenge questions.

### 8. How many apps are there in the data source? 

Print the # of observations of the data.

*Hint: Your code should return the number 7197.*

In [99]:
data.shape[0]  # función de NumPy que se utiliza para obtener la forma o el tamaño de una matriz. 
               # Esta función devuelve una tupla con el número de filas y columnas de la matriz.


7197

### 9. What is the average rating of all apps? 

First, read the `user_rating` column into a varialbe named `user_rating`.

In [109]:
# Métrica utilizada para medir la satisfacción de los usuarios con un producto o servicio

user_rating = data['user_rating']



Now you can calculate the average of the `user_rating` data.

Your code should return 3.526955675976101

In [110]:
# Función de NumPy que se utiliza para calcular el promedio de las calificaciones de los usuarios

user_rating.mean()

3.526955675976101

### 10. How many apps have an average rating no less than 4?

First, filter `user_rating` where its value >= 4. 

Assign the filtered dataframe to a new variable called `user_rating_high`.

In [102]:
#Expresión de Python que se utiliza para obtener las calificaciones de los usuarios que son iguales o superiores a 4. 
#Esta expresión primero filtra la matriz de calificaciones de los usuarios para obtener aquellas 
#calificaciones que son iguales o superiores a 4, y luego devuelve la matriz filtrada. 
#Esta expresión es útil para obtener una visión general de la satisfacción de los usuarios con un producto o servicio


user_rating_high = user_rating[user_rating >=4]
user_rating_high

0       4.0
1       4.0
3       4.0
4       4.5
5       4.0
       ... 
7192    4.5
7193    4.5
7194    4.5
7195    4.5
7196    5.0
Name: user_rating, Length: 4781, dtype: float64

Now obtain the length of `user_rating_high` which should return 4781.

In [104]:
#Calcula el número de elementos en un objeto.

len(user_rating_high)

4781

### 11. How many genres are there in total for all the apps?

Define a new variable named `genres` that contains the `prime_genre` column of `data`. Google for how to obtain unique values of a dataframe column. 

In [103]:
#Variable contendrá una lista de los géneros principales de los datos del conjunto de datos

genres = data['prime_genre']

Print the length of the unique values of `genres`. Your code should return 23.

In [105]:
# Expresión de Python que se utiliza para calcular el número de géneros únicos en un conjunto de datos. 
# Esta expresión primero obtiene los géneros únicos del conjunto de datos utilizando la función .unique(), 
# y luego calcula el número de géneros únicos utilizando la función len(). 
# Esta expresión es útil para obtener una visión general de la diversidad de géneros en un conjunto de datos.

n_genres = len(genres.unique())
print(n_genres)

23


### 12. What are the top 3 genres that have the most number of apps?

What you want to do is to count the number of occurrences of each unique genre values. Because you already know how to obtain the unique genre values, you can of course count the # of apps of each genre one by one. However, Pandas has a convient function to let you count all values of a dataframe column with a single command. Google for "pandas count values" to find the solution. Your code should return the following:

```
Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64
```

In [106]:
# Expresión de Python que se utiliza para contar el número de apariciones de cada género en un conjunto de datos. 
# Esta expresión primero obtiene los valores únicos del género del conjunto de datos utilizando la función .value_counts(), 
# y luego cuenta el número de apariciones de cada género. Esta expresión es útil para obtener una visión general de 
# la distribución de los géneros en un conjunto de datos.

data['prime_genre'].value_counts()

Games                3862
Entertainment         535
Education             453
Photo & Video         349
Utilities             248
Health & Fitness      180
Productivity          178
Social Networking     167
Lifestyle             144
Music                 138
Shopping              122
Sports                114
Book                  112
Finance               104
Travel                 81
News                   75
Weather                72
Reference              64
Food & Drink           63
Business               57
Navigation             46
Medical                23
Catalogs               10
Name: prime_genre, dtype: int64

### 13. Which genre is most likely to contain free apps?

First, filter `data` where the price is 0.00. Assign the filtered data to a new variable called `free_apps`. Then count the values in `free_apps`. Your code should return:

```
Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Navigation             20
Reference              20
Business               20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64
```

In [107]:
# Expresión de Python que se utiliza para contar el número de apariciones de cada género en un conjunto de 
# datos de aplicaciones gratuitas. 
# Esta expresión primero filtra el conjunto de datos para obtener solo las aplicaciones gratuitas, 
# luego obtiene los valores únicos del género de las aplicaciones gratuitas utilizando la función .value_counts(), 
# y finalmente cuenta el número de apariciones de cada género. Esta expresión es útil para obtener una visión general de
# la distribución de los géneros en un conjunto de datos de aplicaciones gratuitas

free_apps = data[data['price'] == 0]
free_apps.prime_genre.value_counts()  

Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Business               20
Reference              20
Navigation             20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64

### 14. Now you can calculate the proportion of the free apps in each genre based on the value counts you obtained in the previous two steps. 

Challenge yourself by achieving that with one line of code. The output should look like:

```
Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64
```

The numbers are interesting, aren't they?

In [108]:
# Esta línea de código se usa para calcular la proporción de aplicaciones gratuitas en relación con el total de aplicaciones para 
# cada género. Primero, cuenta el número de aplicaciones gratuitas para cada género usando 
# `free_apps['prime_genre'].value_counts()`. Luego, cuenta el número total de aplicaciones para cada género
# usando `data['prime_genre'].value_counts()`. Finalmente, divide el número de aplicaciones gratuitas entre el número 
# total de aplicaciones para cada género y ordena los resultados de mayor a menor usando `sort_values(ascending = False)`

(free_apps['prime_genre'].value_counts()/data['prime_genre'].value_counts()).sort_values(ascending = False)


Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64

### 15. If a developer tries to make money by developing and selling Apple Store apps, in which genre should s/he develop the apps? Please assume all apps cost the same amount of time and expense to develop.

We will leave this question to you. There are several way to solve it. Ideally your output should look like below:

```
    average_price              genre
21       8.776087            Medical
11       5.116316           Business
4        4.836875          Reference
6        4.835435              Music
1        4.330562       Productivity
15       4.124783         Navigation
16       4.028234          Education
12       1.916444   Health & Fitness
20       1.790536               Book
7        1.647621          Utilities
2        1.605417            Weather
18       1.552381       Food & Drink
14       1.473295      Photo & Video
0        1.432923              Games
8        1.120370             Travel
10       0.953070             Sports
13       0.889701      Entertainment
17       0.885417          Lifestyle
22       0.799000           Catalogs
19       0.517733               News
5        0.421154            Finance
9        0.339880  Social Networking
3        0.016311           Shopping
```

SyntaxError: positional argument follows keyword argument (1142005273.py, line 6)